version: '3'

services:
  move-core-api:
    image: tokome/move_core_service:0.1.0.alpha-3
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    restart: always
    expose:
      - "5000"
    env_file:
      - .env.move_core_service
    networks:
      - move-internal-net

networks:
  move-internal-net:
    external: true
