version: '3'

services:
  tokome-core-api:
    image: index.docker.io/tokome/tkm_core_service:${TOKOME_CORE_API_TAG}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    restart: always
    expose:
      - "5000"
    env_file:
      - .env.tkm_core_service
    networks:
      - tkm-internal-net

networks:
  tkm-internal-net:
    external: true
